//
//  DetailView.swift
//  EduAnimalSwiftDev
//
//  Created by MacBook Pro on 02/05/24.
//

import SwiftUI
import AVFoundation

struct DetailView: View {
    @StateObject private var animalDescVM = AnimalDescVM()
    @State var selectedAnimal: String
    
    @State private var geminiAIKey = UserDefaults.standard.string(forKey: "GeminiAIKey")
    
    var body: some View {
        Group {
            HStack(spacing: 24) {
                Text(selectedAnimal.uppercased())
                    .font(.largeTitle)
                    .fontWeight(.heavy)
                    .background(
                        Color.teal
                            .frame(height: 6)
                            .offset(y: 24)
                    )
                    .padding(.vertical, 24)
                
                
                Image(systemName: "speaker.wave.2.circle.fill")
                    .foregroundStyle(.teal)
                    .imageScale(.large)
                    .onTapGesture {
                        playAudio(fileName: selectedAnimal, fileFormat: "mp3")
                    }
            }
            if let apiKey = geminiAIKey, !apiKey.isEmpty {
                // Show the TextEditor and other content if API key is present
                Section {
                    TextEditor(text: $animalDescVM.factText)
                        .font(.system(.headline, design: .rounded))
                        .foregroundStyle(.teal)
                        .background(
                            RoundedRectangle(cornerRadius: 12.0)
                                .stroke(Color.teal, lineWidth: 5)
                                .frame(height: 200)
                        )
                        .overlay {
                            animalDescVM.isLoading ? ProgressView() : nil
                        }
                        .task {
                            await animalDescVM.generateFact(animal: selectedAnimal)
                        }
                    
                    
                } header: {
                    Text("Did you know?")
                } footer: {
                    Text("This fact is being generated by Gemini AI.")
                }
                .padding()
            } else {
                // Show a message asking the user to input API key in settings
                Text("Please input your API key in settings.")
                    .foregroundColor(.red)
                    .padding()
            }
        }

    }
}

#Preview {
    let animals: [Animals] = Bundle.main.decode("animals.json")
    return DetailView(selectedAnimal: "cat")
}
